### ISSUE TITLE
Trying to equip an item not in inventory when equipment already has at least one entry will cause an exception

### ISSUE THREAD

**Issue by modle** [modle/TextAdventure#1]
77c10a978e5cf41617b88bbb779959f0b66502c6

Exception in thread "main" java.lang.NullPointerException
	at Equipment.equipItem(Equipment.java:41)
	at Main.main(Main.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

Process finished with exit code 1

**Comment by modle** [comment]
line 41 in Equipment is trying to use item.getSlot() for comparison to the getKey() but item is null

**Comment by modle** [comment]
closed with b0114f4e7eb3fb932478587f23801594b8e7b052
